package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "nsvims")
public class Department implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer departmentSn;
    private int version;
    private String departmentName;
    private String departmentId;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "department_sn", unique = true, nullable = false)
    public Integer getDepartmentSn() {
        return this.departmentSn;
    }

    public void setDepartmentSn(Integer departmentSn) {
        this.departmentSn = departmentSn;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "department_name", nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Column(name = "department_id", nullable = false, length = 10)
    @NotNull
    @Length(max = 10)
    public String getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

}
