package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeRole generated by hbm2java
 */
@Entity
@Table(name = "employee_role", catalog = "nsvims")
public class EmployeeRole implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private Integer employeeRoleSn;
    private int sysUserSn;
    private int roleSn;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "employee_role_sn", unique = true, nullable = false)
    public Integer getEmployeeRoleSn() {
        return this.employeeRoleSn;
    }

    public void setEmployeeRoleSn(Integer employeeRoleSn) {
        this.employeeRoleSn = employeeRoleSn;
    }

    @Column(name = "sys_user_sn", nullable = false)
    public int getSysUserSn() {
        return this.sysUserSn;
    }

    public void setSysUserSn(int sysUserSn) {
        this.sysUserSn = sysUserSn;
    }

    @Column(name = "role_sn", nullable = false)
    public int getRoleSn() {
        return this.roleSn;
    }

    public void setRoleSn(int roleSn) {
        this.roleSn = roleSn;
    }

}
