package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EmployeeCertificate generated by hbm2java
 */
@Entity
@Table(name = "employee_certificate", catalog = "nsvims")
public class EmployeeCertificate implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private Integer employeeCertificateSn;
    private int employeeInfoSn;
    private String certificateName;
    private String issuingAuthority;
    private Date gentTime;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "employee_certificate_sn", unique = true, nullable = false)
    public Integer getEmployeeCertificateSn() {
        return this.employeeCertificateSn;
    }

    public void setEmployeeCertificateSn(Integer employeeCertificateSn) {
        this.employeeCertificateSn = employeeCertificateSn;
    }

    @Column(name = "employee_info_sn", nullable = false)
    public int getEmployeeInfoSn() {
        return this.employeeInfoSn;
    }

    public void setEmployeeInfoSn(int employeeInfoSn) {
        this.employeeInfoSn = employeeInfoSn;
    }

    @Column(name = "certificate_name", nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getCertificateName() {
        return this.certificateName;
    }

    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName;
    }

    @Column(name = "Issuing_authority", nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getIssuingAuthority() {
        return this.issuingAuthority;
    }

    public void setIssuingAuthority(String issuingAuthority) {
        this.issuingAuthority = issuingAuthority;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "gent_time", nullable = false, length = 10)
    @NotNull
    public Date getGentTime() {
        return this.gentTime;
    }

    public void setGentTime(Date gentTime) {
        this.gentTime = gentTime;
    }

}
