package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LeaveAndOvertimeDetail generated by hbm2java
 */
@Entity
@Table(name = "leave_and_overtime_detail", catalog = "nsvims")
public class LeaveAndOvertimeDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer laodSn;
    private int workLogDetailSerialNum;
    private String laodDiscription;
    private char llaodFlag;
    private float laodHours;
    private Date laodStartTime;
    private Date laodEndTime;
    private Character workPart;
    private String projectId;
    private Character workPlace;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "laod_sn", unique = true, nullable = false)
    public Integer getLaodSn() {
        return this.laodSn;
    }

    public void setLaodSn(Integer laodSn) {
        this.laodSn = laodSn;
    }

    @Column(name = "work_log_detail_serial_num", nullable = false)
    public int getWorkLogDetailSerialNum() {
        return this.workLogDetailSerialNum;
    }

    public void setWorkLogDetailSerialNum(int workLogDetailSerialNum) {
        this.workLogDetailSerialNum = workLogDetailSerialNum;
    }

    @Column(name = "laod_discription", nullable = false, length = 500)
    @NotNull
    @Length(max = 500)
    public String getLaodDiscription() {
        return this.laodDiscription;
    }

    public void setLaodDiscription(String laodDiscription) {
        this.laodDiscription = laodDiscription;
    }

    @Column(name = "llaod_flag", nullable = false, length = 1)
    public char getLlaodFlag() {
        return this.llaodFlag;
    }

    public void setLlaodFlag(char llaodFlag) {
        this.llaodFlag = llaodFlag;
    }

    @Column(name = "laod_hours", nullable = false, precision = 12, scale = 0)
    public float getLaodHours() {
        return this.laodHours;
    }

    public void setLaodHours(float laodHours) {
        this.laodHours = laodHours;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "laod_startTime", nullable = false, length = 8)
    @NotNull
    public Date getLaodStartTime() {
        return this.laodStartTime;
    }

    public void setLaodStartTime(Date laodStartTime) {
        this.laodStartTime = laodStartTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "laod_endTime", nullable = false, length = 8)
    @NotNull
    public Date getLaodEndTime() {
        return this.laodEndTime;
    }

    public void setLaodEndTime(Date laodEndTime) {
        this.laodEndTime = laodEndTime;
    }

    @Column(name = "work_part", length = 1)
    public Character getWorkPart() {
        return this.workPart;
    }

    public void setWorkPart(Character workPart) {
        this.workPart = workPart;
    }

    @Column(name = "project_id", length = 50)
    @Length(max = 50)
    public String getProjectId() {
        return this.projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    @Column(name = "work_place", length = 1)
    public Character getWorkPlace() {
        return this.workPlace;
    }

    public void setWorkPlace(Character workPlace) {
        this.workPlace = workPlace;
    }

}
