package cn.com.nsv.ejb.entity;

// Generated 2014-5-6 13:54:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MealSupplementReport generated by hbm2java
 */
@Entity
@Table(name = "meal_supplement_report", catalog = "nsvims")
public class MealSupplementReport implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private Integer mealSupplementReportSn;
    private String employeeId;
    private String yearAndMonth;
    private int normalWorkdayCount;
    private int employeeMonthWorkdayCount;
    private float normalWorkdayMealSupplement;
    private int overtimeWorkdayCount;
    private float overtimeWorkdayMealSupplement;
    private int overtimeWeekdayCount;
    private float overtimeWeekdayMealSupplement;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "meal_supplement_report_sn", unique = true, nullable = false)
    public Integer getMealSupplementReportSn() {
        return this.mealSupplementReportSn;
    }

    public void setMealSupplementReportSn(Integer mealSupplementReportSn) {
        this.mealSupplementReportSn = mealSupplementReportSn;
    }

    @Column(name = "employee_id", nullable = false, length = 20)
    @NotNull
    @Length(max = 20)
    public String getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "year_and_month", nullable = false, length = 7)
    @NotNull
    @Length(max = 7)
    public String getYearAndMonth() {
        return this.yearAndMonth;
    }

    public void setYearAndMonth(String yearAndMonth) {
        this.yearAndMonth = yearAndMonth;
    }

    @Column(name = "normal_workday_count", nullable = false)
    public int getNormalWorkdayCount() {
        return this.normalWorkdayCount;
    }

    public void setNormalWorkdayCount(int normalWorkdayCount) {
        this.normalWorkdayCount = normalWorkdayCount;
    }

    @Column(name = "employee_month_workday_count", nullable = false)
    public int getEmployeeMonthWorkdayCount() {
        return this.employeeMonthWorkdayCount;
    }

    public void setEmployeeMonthWorkdayCount(int employeeMonthWorkdayCount) {
        this.employeeMonthWorkdayCount = employeeMonthWorkdayCount;
    }

    @Column(name = "normal_workday_meal_supplement", nullable = false, precision = 12, scale = 0)
    public float getNormalWorkdayMealSupplement() {
        return this.normalWorkdayMealSupplement;
    }

    public void setNormalWorkdayMealSupplement(float normalWorkdayMealSupplement) {
        this.normalWorkdayMealSupplement = normalWorkdayMealSupplement;
    }

    @Column(name = "overtime_workday_count", nullable = false)
    public int getOvertimeWorkdayCount() {
        return this.overtimeWorkdayCount;
    }

    public void setOvertimeWorkdayCount(int overtimeWorkdayCount) {
        this.overtimeWorkdayCount = overtimeWorkdayCount;
    }

    @Column(name = "overtime_workday_meal_supplement", nullable = false, precision = 12, scale = 0)
    public float getOvertimeWorkdayMealSupplement() {
        return this.overtimeWorkdayMealSupplement;
    }

    public void setOvertimeWorkdayMealSupplement(float overtimeWorkdayMealSupplement) {
        this.overtimeWorkdayMealSupplement = overtimeWorkdayMealSupplement;
    }

    @Column(name = "overtime_weekday_count", nullable = false)
    public int getOvertimeWeekdayCount() {
        return this.overtimeWeekdayCount;
    }

    public void setOvertimeWeekdayCount(int overtimeWeekdayCount) {
        this.overtimeWeekdayCount = overtimeWeekdayCount;
    }

    @Column(name = "overtime_weekday_meal_supplement", nullable = false, precision = 12, scale = 0)
    public float getOvertimeWeekdayMealSupplement() {
        return this.overtimeWeekdayMealSupplement;
    }

    public void setOvertimeWeekdayMealSupplement(float overtimeWeekdayMealSupplement) {
        this.overtimeWeekdayMealSupplement = overtimeWeekdayMealSupplement;
    }

}
