package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "nsvims")
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer roleSn;
    private int version;
    private String roleName;
    private char roleType;
    private String recordMemo;
    private char roleStatus;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "role_sn", unique = true, nullable = false)
    public Integer getRoleSn() {
        return this.roleSn;
    }

    public void setRoleSn(Integer roleSn) {
        this.roleSn = roleSn;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "role_name", nullable = false, length = 50)
    @NotNull
    @Length(max = 50)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "role_type", nullable = false, length = 1)
    public char getRoleType() {
        return this.roleType;
    }

    public void setRoleType(char roleType) {
        this.roleType = roleType;
    }

    @Column(name = "record_memo", length = 500)
    @Length(max = 500)
    public String getRecordMemo() {
        return this.recordMemo;
    }

    public void setRecordMemo(String recordMemo) {
        this.recordMemo = recordMemo;
    }

    @Column(name = "role_status", nullable = false, length = 1)
    public char getRoleStatus() {
        return this.roleStatus;
    }

    public void setRoleStatus(char roleStatus) {
        this.roleStatus = roleStatus;
    }

}
