package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * RoleFun generated by hbm2java
 */
@Entity
@Table(name = "role_fun", catalog = "nsvims")
public class RoleFun implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer roleFunSn;
    private int funSerialNum;
    private int roleSn;
    private String rolePermission;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "role_fun_sn", unique = true, nullable = false)
    public Integer getRoleFunSn() {
        return this.roleFunSn;
    }

    public void setRoleFunSn(Integer roleFunSn) {
        this.roleFunSn = roleFunSn;
    }

    @Column(name = "fun_serial_num", nullable = false)
    public int getFunSerialNum() {
        return this.funSerialNum;
    }

    public void setFunSerialNum(int funSerialNum) {
        this.funSerialNum = funSerialNum;
    }

    @Column(name = "role_sn", nullable = false)
    public int getRoleSn() {
        return this.roleSn;
    }

    public void setRoleSn(int roleSn) {
        this.roleSn = roleSn;
    }

    @Column(name = "role_permission", nullable = false, length = 2)
    @NotNull
    @Length(max = 2)
    public String getRolePermission() {
        return this.rolePermission;
    }

    public void setRolePermission(String rolePermission) {
        this.rolePermission = rolePermission;
    }

}
