package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TaFunctions generated by hbm2java
 */
@Entity
@Table(name = "ta_functions", catalog = "nsvims")
public class TaFunctions implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer funSerialNum;
    private String funId;
    private String funName;
    private char displayFlag;
    private String linkPage;
    private String funDescription;
    private String parentFunId;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "fun_serial_num", unique = true, nullable = false)
    public Integer getFunSerialNum() {
        return this.funSerialNum;
    }

    public void setFunSerialNum(Integer funSerialNum) {
        this.funSerialNum = funSerialNum;
    }

    @Column(name = "fun_id", nullable = false, length = 200)
    @NotNull
    @Length(max = 200)
    public String getFunId() {
        return this.funId;
    }

    public void setFunId(String funId) {
        this.funId = funId;
    }

    @Column(name = "fun_name", nullable = false, length = 200)
    @NotNull
    @Length(max = 200)
    public String getFunName() {
        return this.funName;
    }

    public void setFunName(String funName) {
        this.funName = funName;
    }

    @Column(name = "display_flag", nullable = false, length = 1)
    public char getDisplayFlag() {
        return this.displayFlag;
    }

    public void setDisplayFlag(char displayFlag) {
        this.displayFlag = displayFlag;
    }

    @Column(name = "link_page", length = 500)
    @Length(max = 500)
    public String getLinkPage() {
        return this.linkPage;
    }

    public void setLinkPage(String linkPage) {
        this.linkPage = linkPage;
    }

    @Column(name = "fun_description", length = 1000)
    @Length(max = 1000)
    public String getFunDescription() {
        return this.funDescription;
    }

    public void setFunDescription(String funDescription) {
        this.funDescription = funDescription;
    }

    @Column(name = "parent_fun_id", length = 200)
    @Length(max = 200)
    public String getParentFunId() {
        return this.parentFunId;
    }

    public void setParentFunId(String parentFunId) {
        this.parentFunId = parentFunId;
    }

}
