package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserDepartment generated by hbm2java
 */
@Entity
@Table(name = "user_department", catalog = "nsvims")
public class UserDepartment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer udSn;
    private int departmentSn;
    private int sysUserSn;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ud_sn", unique = true, nullable = false)
    public Integer getUdSn() {
        return this.udSn;
    }

    public void setUdSn(Integer udSn) {
        this.udSn = udSn;
    }

    @Column(name = "department_sn", nullable = false)
    public int getDepartmentSn() {
        return this.departmentSn;
    }

    public void setDepartmentSn(int departmentSn) {
        this.departmentSn = departmentSn;
    }

    @Column(name = "sys_user_sn", nullable = false)
    public int getSysUserSn() {
        return this.sysUserSn;
    }

    public void setSysUserSn(int sysUserSn) {
        this.sysUserSn = sysUserSn;
    }

}
