package cn.com.nsv.ejb.entity;

// Generated 2014-4-30 10:13:13 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkLogRecord generated by hbm2java
 */
@Entity
@Table(name = "work_log_record", catalog = "nsvims")
public class WorkLogRecord implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int workLogRecordSn;
    private int workLogSn;
    private char workLogRecordStatus;
    private String workLogRecordMemo;
    private String employeeId;


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "work_log_record_sn", unique = true, nullable = false)
    public int getWorkLogRecordSn() {
        return this.workLogRecordSn;
    }

    public void setWorkLogRecordSn(int workLogRecordSn) {
        this.workLogRecordSn = workLogRecordSn;
    }

    @Column(name = "work_log_sn", nullable = false)
    public int getWorkLogSn() {
        return this.workLogSn;
    }

    public void setWorkLogSn(int workLogSn) {
        this.workLogSn = workLogSn;
    }

    @Column(name = "work_log_record_status", nullable = false, length = 1)
    public char getWorkLogRecordStatus() {
        return this.workLogRecordStatus;
    }

    public void setWorkLogRecordStatus(char workLogRecordStatus) {
        this.workLogRecordStatus = workLogRecordStatus;
    }

    @Column(name = "work_log_record_memo", length = 100)
    @Length(max = 100)
    public String getWorkLogRecordMemo() {
        return this.workLogRecordMemo;
    }

    public void setWorkLogRecordMemo(String workLogRecordMemo) {
        this.workLogRecordMemo = workLogRecordMemo;
    }

    @Column(name = "employee_id", nullable = false, length = 20)
    @NotNull
    @Length(max = 20)
    public String getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

}
