package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkLog generated by hbm2java
 */
@Entity
@Table(name = "work_log", catalog = "nsvims")
public class WorkLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer workLogSn;
    private int version;
    private String workLogYear;
    private int workLogWeek;
    private char workLogStatus;
    private String employeeId;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "work_log_sn", unique = true, nullable = false)
    public Integer getWorkLogSn() {
        return this.workLogSn;
    }

    public void setWorkLogSn(Integer workLogSn) {
        this.workLogSn = workLogSn;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Column(name = "work_log_year", nullable = false, length = 4)
    @NotNull
    @Length(max = 4)
    public String getWorkLogYear() {
        return this.workLogYear;
    }

    public void setWorkLogYear(String workLogYear) {
        this.workLogYear = workLogYear;
    }

    @Column(name = "work_log_week", nullable = false)
    public int getWorkLogWeek() {
        return this.workLogWeek;
    }

    public void setWorkLogWeek(int workLogWeek) {
        this.workLogWeek = workLogWeek;
    }

    @Column(name = "work_log_status", nullable = false, length = 1)
    public char getWorkLogStatus() {
        return this.workLogStatus;
    }

    public void setWorkLogStatus(char workLogStatus) {
        this.workLogStatus = workLogStatus;
    }

    @Column(name = "employee_id", nullable = false, length = 20)
    @NotNull
    @Length(max = 20)
    public String getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

}
