package cn.com.nsv.ejb.entity;

// Generated 2014-3-19 10:42:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * WorkLogDetail generated by hbm2java
 */
@Entity
@Table(name = "work_log_detail", catalog = "nsvims")
public class WorkLogDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer workLogDetailSerialNum;
    private int workLogSn;
    private Date workDate;
    private String workWeekday;
    private float dailyHours;
    private float dailiyMealSupplement;
    private int dateVersion;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "work_log_detail_serial_num", unique = true, nullable = false)
    public Integer getWorkLogDetailSerialNum() {
        return this.workLogDetailSerialNum;
    }

    public void setWorkLogDetailSerialNum(Integer workLogDetailSerialNum) {
        this.workLogDetailSerialNum = workLogDetailSerialNum;
    }

    @Column(name = "work_log_sn", nullable = false)
    public int getWorkLogSn() {
        return this.workLogSn;
    }

    public void setWorkLogSn(int workLogSn) {
        this.workLogSn = workLogSn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "work_date", nullable = false, length = 19)
    @NotNull
    public Date getWorkDate() {
        return this.workDate;
    }

    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }
    
    @Column(name = "work_weekday", nullable = false, length = 10)
    @NotNull
    @Length(max = 10)
    public String getWorkWeekday() {
        return this.workWeekday;
    }

    public void setWorkWeekday(String workWeekday) {
        this.workWeekday = workWeekday;
    }

    @Column(name = "daily_hours", nullable = false, precision = 12, scale = 0)
    public float getDailyHours() {
        return this.dailyHours;
    }

    public void setDailyHours(float dailyHours) {
        this.dailyHours = dailyHours;
    }

    @Column(name = "dailiy_meal_supplement", nullable = false, precision = 12, scale = 0)
    public float getDailiyMealSupplement() {
        return this.dailiyMealSupplement;
    }

    public void setDailiyMealSupplement(float dailiyMealSupplement) {
        this.dailiyMealSupplement = dailiyMealSupplement;
    }
    
    @Column(name = "date_version", nullable = false)
    public int getDateVersion() {
        return this.dateVersion;
    }

    public void setDateVersion(int dateVersion) {
        this.dateVersion = dateVersion;
    }

}
